# Generated by Django 5.1.15 on 2026-04-30 20:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_library", "0002_mediaasset_is_starred_mediaasset_organization_and_more"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="gtm/partners/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "gtm_partner",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("homepage_url", models.URLField(blank=True)),
                ("docs_url", models.URLField(blank=True)),
                ("pricing_url", models.URLField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="products", to="gtm.partner"
                    ),
                ),
            ],
            options={
                "db_table": "gtm_product",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProblemSolution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("problem_statement", models.TextField(help_text="Markdown. The pain in the customer's words.")),
                ("solution_statement", models.TextField(help_text="Markdown. How the product solves it.")),
                ("target_persona", models.CharField(max_length=200)),
                (
                    "pain_intensity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Mild"),
                            (2, "2 - Moderate"),
                            (3, "3 - Significant"),
                            (4, "4 - Severe"),
                            (5, "5 - Critical"),
                        ],
                        default=3,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="problem_solutions", to="gtm.product"
                    ),
                ),
            ],
            options={
                "db_table": "gtm_problem_solution",
                "ordering": ["-is_primary", "-pain_intensity", "target_persona"],
            },
        ),
        migrations.CreateModel(
            name="GTMPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "audiences",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {persona, role_titles, company_size, industries, watering_holes}",
                    ),
                ),
                (
                    "value_props",
                    models.JSONField(
                        blank=True, default=list, help_text="Ordered list of value-proposition strings (max 8)"
                    ),
                ),
                (
                    "proof_points",
                    models.JSONField(
                        blank=True, default=list, help_text="List of {claim, evidence_url, evidence_type}"
                    ),
                ),
                (
                    "voice",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{tone, formality_1_to_5, humor_allowed, emoji_policy, we_vs_i, reading_level}",
                    ),
                ),
                ("do_say", models.JSONField(blank=True, default=list, help_text="Preferred phrases / framings")),
                (
                    "do_not_say",
                    models.JSONField(
                        blank=True, default=list, help_text="Banned words, competitor names to avoid, regulated claims"
                    ),
                ),
                (
                    "competitors",
                    models.JSONField(blank=True, default=list, help_text="List of {name, positioning_against}"),
                ),
                ("keywords_seo", models.JSONField(blank=True, default=list)),
                ("cta_library", models.JSONField(blank=True, default=list, help_text="List of {label, url, intent}")),
                ("compliance_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gtm_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gtm_plans_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_media_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gtm_plans",
                        to="media_library.mediafolder",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="gtm_plans", to="gtm.partner"
                    ),
                ),
                (
                    "problem_solution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gtm_plans",
                        to="gtm.problemsolution",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = partner-wide plan",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gtm_plans",
                        to="gtm.product",
                    ),
                ),
            ],
            options={
                "db_table": "gtm_plan",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GTMPlanRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "snapshot",
                    models.JSONField(help_text="Full GTMPlan state at the time of revision (JSON-serialized)"),
                ),
                (
                    "diff_summary",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable summary of changes from the previous revision",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gtm_plan_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="gtm.gtmplan"
                    ),
                ),
            ],
            options={
                "db_table": "gtm_plan_revision",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["plan", "-created_at"], name="gtm_plan_re_plan_id_ac5b53_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["workspace", "is_archived"], name="gtm_partner_workspa_357d92_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="partner",
            unique_together={("workspace", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("partner", "slug")},
        ),
        migrations.AddConstraint(
            model_name="problemsolution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="gtm_problem_solution_one_primary_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="gtmplan",
            index=models.Index(fields=["workspace", "status"], name="gtm_plan_workspa_df7f48_idx"),
        ),
        migrations.AddIndex(
            model_name="gtmplan",
            index=models.Index(fields=["partner", "product"], name="gtm_plan_partner_0cd4ac_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gtmplan",
            unique_together={("workspace", "slug")},
        ),
    ]
