# Generated by Django 5.1.15 on 2026-04-30 20:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gtm", "0001_initial"),
        ("organizations", "0001_initial"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIWorkspaceConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider_preference",
                    models.JSONField(
                        blank=True, default=list, help_text="Ordered list of providers, e.g. ['anthropic', 'openai']"
                    ),
                ),
                ("default_model", models.CharField(default="claude-sonnet-4-6", max_length=100)),
                (
                    "monthly_usd_cap",
                    models.PositiveIntegerField(default=25, help_text="Whole USD per month per workspace"),
                ),
                ("current_month_spend_micro", models.PositiveBigIntegerField(default=0)),
                ("spend_window_start", models.DateField(default=django.utils.timezone.now)),
                ("routed_via_shroud", models.BooleanField(default=False)),
                ("shroud_agent_id", models.CharField(blank=True, max_length=200)),
                ("use_oneclaw_vault", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ai_config", to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "ai_workspace_config",
            },
        ),
        migrations.CreateModel(
            name="AICredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ai_anthropic", "Anthropic API key"),
                            ("ai_openai", "OpenAI API key"),
                            ("ai_google", "Google AI API key"),
                            ("ai_shroud_endpoint", "1Claw Shroud endpoint"),
                            ("ai_shroud_agent_token", "1Claw Shroud agent token"),
                            ("ai_1claw_vault_token", "1Claw Vault agent token"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "credentials",
                    apps.common.encryption.EncryptedJSONField(
                        default=dict, help_text="Encrypted JSON, e.g. {'api_key': '...'} or {'endpoint': '...'}"
                    ),
                ),
                ("is_configured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_credentials",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_credential",
                "unique_together": {("organization", "kind")},
            },
        ),
        migrations.CreateModel(
            name="AIGeneration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("caption", "Caption"),
                            ("multi_platform", "Multi-Platform"),
                            ("hook", "Hook"),
                            ("cta", "CTA"),
                            ("hashtags", "Hashtags"),
                            ("brief_expand", "Brief Expand"),
                            ("idea_seed", "Idea Seed"),
                            ("reply_draft", "Reply Draft"),
                            ("image_prompt", "Image Prompt"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_payload", models.JSONField(default=dict, help_text="Brief, options, etc.")),
                ("system_prompt_version", models.CharField(default="v0", max_length=50)),
                ("provider", models.CharField(help_text="anthropic / openai / google", max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("routed_via_shroud", models.BooleanField(default=False)),
                (
                    "shroud_redactions",
                    models.JSONField(
                        blank=True, default=list, help_text="Verbatim copy of Shroud's redactions array, if present"
                    ),
                ),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd_micro",
                    models.PositiveBigIntegerField(
                        default=0, help_text="USD micro-dollars (1 USD = 1,000,000 micro). Avoids float drift."
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("blocked_by_shroud", "Blocked by Shroud"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gtm_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generations",
                        to="gtm.gtmplan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "ai_generation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["workspace", "kind", "-created_at"], name="ai_generati_workspa_cf458a_idx"),
                    models.Index(fields=["workspace", "-created_at"], name="ai_generati_workspa_5d118b_idx"),
                    models.Index(fields=["status"], name="ai_generati_status_e95323_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIPreset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_gtm_plan",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="gtm.gtmplan"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "ai_preset",
                "ordering": ["name"],
                "unique_together": {("workspace", "actor", "name")},
            },
        ),
    ]
